### ISSUE TITLE
function required: preview image

### ISSUE THREAD

**Issue by Illyrix** [dai-siki/vue-upload-file#3]
在上传操作之前可以预览上传的图片.类似[http://element.eleme.io/#/zh-CN/component/upload](http://element.eleme.io/#/zh-CN/component/upload)

**Comment by dai-siki** [comment]
此插件暂不考虑做功能优化，你可以看看其他更适合的插件。比如：[vue-image-crop-upload](https://github.com/dai-siki/vue-image-crop-upload)
